name: brightpath

services:
  db:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: brightpath
  redis:
    image: redis:7
    ports:
      - '6379:6379'

  kafka:
    image: apache/kafka:3.8.0
    ports:
      - '9092:9092'
