name: brightpath-test

services:
  db:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: brightpath_tests

  redis:
    image: redis:7
    ports:
      - '6379:6379'
