export const businessTypeValues = [
  'B2B',
  'Digital Goods',
  'E-commerce',
  'Education',
  'Financial Services',
  'Food and Beverages',
  'Gaming',
  'Government',
  'Grocery',
  'Health care',
  'Insurance',
  'Jewellery',
  'Logistics',
  'Miscellaneous',
  'Mutual funds/Broking',
  'Non Profit/NGO',
  'Online Gaming',
  'Open and Semi Open Wallet',
  'Pan shop',
  'Pharmacy',
  'Readymade',
  'Real Estate, Housing, Rentals',
  'Retail and Shopping',
  'SaaS',
  'Social Media and Entertainment',
  'Society/Trust/Club/Association',
  'Telecom',
  'Travel and Hospitality',
  'Utilities',
  'Chit Funds',
  'Web host/Domain seller',
  'Professional Services (Doctors, Lawyers, Architects, CAs, and other Professionals)',
] as const;
